In [1]:
import numpy as np

In [62]:
#store hetro vlaues in np array
complex_list = [1,2,3] + [1.,2.,3.] + ['a','b','c']
complex_list

[1, 2, 3, 1.0, 2.0, 3.0, 'a', 'b', 'c']

In [63]:
Array_2 = np.array(complex_list[:3])

In [64]:
Array_2

array([1, 2, 3])

In [65]:
print ('complex_list[:3]', Array_2.dtype)

complex_list[:3] int64


In [66]:
Array_2 = np.array(complex_list[:6])
Array_2

array([1., 2., 3., 1., 2., 3.])

In [67]:
array_1=np.array(complex_list)
array_1

array(['1', '2', '3', '1.0', '2.0', '3.0', 'a', 'b', 'c'], dtype='<U32')

In [68]:
# for i in array_1:
#     print(i.dtype())

In [69]:
for i in range(0,len(array_1)):
    if isinstance(array_1[i],np.number):
        print("yes")
    else:
        print("No")


No
No
No
No
No
No
No
No
No


In [70]:
a_list = [[[1,2],[3,4],[5,6]],
[[7,8],[9,10],[11,12]]]

In [71]:
array_from_list=np.array(a_list)
array_from_list

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [72]:
array_from_dic=np.array({1:2,3:4,5:6}.items())
array_from_dic

array(dict_items([(1, 2), (3, 4), (5, 6)]), dtype=object)

In [73]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
#
fractions = np.linspace(start=0, stop=1, num=10)
fractions

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [43]:
growth = np.logspace(start=0, stop=1, num=10, base=10.0)
growth

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [49]:
%%time
std_gaussian = np.random.normal(0,1,100)
std_gaussian

CPU times: user 191 µs, sys: 30 µs, total: 221 µs
Wall time: 188 µs


array([ 1.14683591, -0.08558441,  0.61981196,  0.30356141, -0.31547921,
        0.78151234, -0.5137851 , -0.03536004,  0.1520358 , -0.56258397,
        0.41472411,  1.02109718,  0.67797068,  1.03289391,  0.76216943,
        1.34565318, -1.32624098, -1.71212844,  0.23529641,  0.67412234,
        0.29419393, -1.46015262, -0.66893195,  0.75867351, -1.80089712,
        0.8311265 ,  1.97702443,  2.09040987,  0.64836928, -0.83092037,
        0.44299536,  0.24880507,  0.51647657, -0.75755032, -1.83258526,
       -0.78936089,  0.79940013, -1.04288365, -2.28535875,  0.28452918,
       -0.05511239, -0.72070247, -0.98835639,  0.39783426,  0.71096776,
       -0.92621978,  1.07612237, -0.84292519,  1.41842011, -0.86180737,
       -0.42780251, -0.48492682, -1.27890702,  1.56346864, -0.46231539,
       -0.15223456,  0.92391053,  1.32526893, -0.74327687,  0.77758138,
       -0.04434513,  1.05149863,  1.28105312, -1.57774254,  0.68217223,
       -0.59434216, -1.78833397, -1.85284037, -0.72199839, -0.43

In [57]:
gaussian = np.random.normal(loc=1.0, scale= 3.0, size=(3,3))
gaussian
# The loc parameter stands for the mean and the scale is actually the standard deviation.

array([[-0.55349705, -0.31132534,  0.83497677],
       [ 0.60265531,  1.24831845,  2.25974004],
       [-0.53952187,  0.43927782,  5.99110765]])

In [58]:
std_gaussian_1 = np.random.normal(size=(3,3,3))
std_gaussian_1

array([[[-1.84184789, -0.35755251,  0.5106801 ],
        [-0.68125655, -0.20971616,  1.16532659],
        [ 0.27733429,  2.04861819, -0.91243059]],

       [[-0.43574953,  0.51386322,  1.02719552],
        [ 1.09382583, -0.70587885,  0.87048534],
        [-1.23572726,  1.28049172, -1.08891505]],

       [[-0.18665716, -0.97335821,  0.30812153],
        [-1.58827622, -0.62609445, -0.66933973],
        [-0.19392221, -1.24139857, -0.22162331]]])

In [59]:
# test_x=np.linspace(1,1,num=5)
# test_x
np.linspace(10,11,num=10)

array([10.        , 10.11111111, 10.22222222, 10.33333333, 10.44444444,
       10.55555556, 10.66666667, 10.77777778, 10.88888889, 11.        ])

In [60]:
rand = np.random.uniform(low=0.0, high=1.0, size=(3,3))

In [61]:
rand

array([[0.55016712, 0.46000035, 0.27866451],
       [0.82873577, 0.45342581, 0.10514227],
       [0.47361999, 0.69693983, 0.7839599 ]])