In [37]:
import numpy as np
import csv 
import math

In [2]:
filename="iris.data"

In [11]:
data=np.genfromtxt(filename,delimiter=',', dtype=float)
# for i in data:
#     for j in i:
#         if j==5:
#             print(j)
        

In [14]:
data.shape

(150, 5)

In [18]:
a = np.arange(5).reshape(1,5)

In [19]:
a

array([[0, 1, 2, 3, 4]])

In [20]:
a+=1

In [21]:
a

array([[1, 2, 3, 4, 5]])

In [22]:
a*=2

In [23]:
a

array([[ 2,  4,  6,  8, 10]])

In [24]:
a = np.arange(5).reshape(1,5) + 1

In [25]:
b = np.arange(5).reshape(5,1)+1

In [26]:
a*b

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [27]:
#alternative
a2 = np.array([1,2,3,4,5] * 5).reshape(5,5)

In [28]:
a2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [29]:
np.sum(a2,axis=0)

array([ 5, 10, 15, 20, 25])

In [30]:
np.sum(a2,axis=1)

array([15, 15, 15, 15, 15])

In [35]:
%%timeit
[i+1 for i in range(10**6)]

128 ms ± 58.2 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [36]:
%%timeit
np.arange(10**2)+1

2.84 µs ± 31.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [38]:
%%timeit 
x=[math.sqrt(i) for i in range(10**6)]

265 ms ± 5.16 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [39]:
%%timeit
np.sqrt(np.arange(10**6))

8.28 ms ± 38.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [41]:
M = np.arange(100, dtype=int).reshape(10,10)

In [52]:
# [start_index_included:end_index_exclude:steps]
M[2:5:2,:5]

array([[20, 21, 22, 23, 24],
       [40, 41, 42, 43, 44]])

In [53]:
row_index = (M[:,0]>=20) & (M[:,0]<=80)

In [54]:
col_index = M[0,:]>=5

In [55]:
M[row_index,:][:,col_index]

array([[25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69],
       [75, 76, 77, 78, 79],
       [85, 86, 87, 88, 89]])

In [64]:
dataset = np.arange(50).reshape(10,5)
dataset

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [65]:
single_line = np.arange(1*5).reshape(1,5)
single_line

array([[0, 1, 2, 3, 4]])

In [66]:
a_few_lines = np.arange(3*5).reshape(3,5)
a_few_lines

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
np.vstack((dataset,single_line))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [ 0,  1,  2,  3,  4]])

In [70]:
bias = np.ones(10).reshape(10,1)
bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [71]:
np.hstack((dataset,bias))

array([[ 0.,  1.,  2.,  3.,  4.,  1.],
       [ 5.,  6.,  7.,  8.,  9.,  1.],
       [10., 11., 12., 13., 14.,  1.],
       [15., 16., 17., 18., 19.,  1.],
       [20., 21., 22., 23., 24.,  1.],
       [25., 26., 27., 28., 29.,  1.],
       [30., 31., 32., 33., 34.,  1.],
       [35., 36., 37., 38., 39.,  1.],
       [40., 41., 42., 43., 44.,  1.],
       [45., 46., 47., 48., 49.,  1.]])

In [72]:
bias = np.ones(10)

In [73]:
bias

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [74]:
np.column_stack((dataset,bias))

array([[ 0.,  1.,  2.,  3.,  4.,  1.],
       [ 5.,  6.,  7.,  8.,  9.,  1.],
       [10., 11., 12., 13., 14.,  1.],
       [15., 16., 17., 18., 19.,  1.],
       [20., 21., 22., 23., 24.,  1.],
       [25., 26., 27., 28., 29.,  1.],
       [30., 31., 32., 33., 34.,  1.],
       [35., 36., 37., 38., 39.,  1.],
       [40., 41., 42., 43., 44.,  1.],
       [45., 46., 47., 48., 49.,  1.]])

In [77]:
np.dstack((dataset*1))
#operates on the third axis

array([[[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
        [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
        [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
        [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
        [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]]])